### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by kubitre** [ory/keto#185]
Current version of documentation not contain latest version of Environment variables do which used by configuring and also, documentation not contain information about how i can setup with docker-compose (full-stack example is too old version and not be image of current latest version)

**Comment by aeneasr** [comment]
Would you be open to contribute those?

**Comment by waltaro** [comment]
Just piggybacking off of this issue.. I've noticed that documentation for the `listOryAccessControlPolicies` API is missing the `member` query string.

I understand that it is not part of the struct as defined in [`engine/ladon/doc.go:46`](https://github.com/ory/keto/blob/master/engine/ladon/doc.go#L46), but when calling the API with the `member` query string present, it returns all policies that the member (subject) has access to.

Using the `subject` query string returns only the policies that the subject has access to -- regardless of being a member of a role that has access to the same or more policies.

For example:

- Subject A has access to policies A, B, C.
- Subject A is part of Role A.
- Role A has access to policy D.

Using the `subject` query string will result in policies A, B, and C being returned.
Using the `member` query string will result in policies A, B, C, and D being returned.

Is this intentional behaviour? Or should this be raised as another issue?

Thank you!

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
