### ISSUE TITLE
Roles and Policies Filter by using flavor strategy

### ISSUE THREAD

**Issue by SomaticIT** [ory/keto#186]
**Is your feature request related to a problem? Please describe.**

The actual way to filter `Policies` and `Roles` is very limited. It does not allows to scale and to reuse the system in a big application.

Why?
 1. It does not allow to take advantage of grouping capabilities of ids (`{scope}:{tenantId}:{id}`)
 2. The filtering mecanism is done by the program not the database which will be a point of failure when database grows.

**Describe the solution you'd like**

I think that it could be interesting to filter both `Policies` and `Roles` using given `flavor` strategy in `List` or `Delete` requests.

Eg.: 
 * `GET http://localhost:4466/engines/acp/ory/glob/roles?id=roles:tenantId1:**`. 
    *(Allowing to fetch all roles for given Tenant in a multi-tenant application).*

 * `DELETE http://localhost:4466/engines/acp/ory/glob/roles/roles:tenantId1:**`.
    *(Allowing to delete all roles for given Tenant in a multi-tenant application).*

I think that we should:
1. Apply `flavor` filter in `storage` entities. (eg: [Policy.withIDs](https://github.com/ory/keto/blob/f8c1060903e81a491ecaa85e0624e8c0a32f995e/storage/policy.go#L55))
2. Generate storage query from `flavor` (eg: SQL for postgres)
3. Apply generated filter in [List](https://github.com/ory/keto/blob/f8c1060903e81a491ecaa85e0624e8c0a32f995e/storage/manager_sql.go#L110) and [Delete](https://github.com/ory/keto/blob/f8c1060903e81a491ecaa85e0624e8c0a32f995e/storage/manager_sql.go#L144)
4. Add indexes to increase Postgres performance (`gin` index type).

**Describe alternatives you've considered**

To allow filtering by tenant or other attributes, we could add specials `Subjects` in `Roles` and `Policies` but it's not very efficient and comes with many additional data.

**Additional context**

Little test to generate a `WHERE` clause: https://play.golang.org/p/97E-c3BhbxH

**Comment by SomaticIT** [comment]
I try to contribute as I can.

You can find below an implementation of glob queries in Postgres:
https://dbfiddle.uk/?rdbms=postgres_12&fiddle=05954dc83b80948c56b12e663565286d&hide=1

And an update go `WHERE` generator based on glob queries:
https://play.golang.org/p/_3OC-8Y19xl

**Comment by SomaticIT** [comment]
Note: This issue is an extension of #20 and #124.

**Comment by SomaticIT** [comment]
Use JSONB in Postgres to improve performance (in migration):
```SQL
ALTER TABLE rego_data
    ALTER COLUMN document SET DATA TYPE jsonb USING document::jsonb;
```
Create indexes in Postgres to improve performance (in migration):
```SQL
CREATE INDEX idx_doc_id ON document USING BTREE ((document->>'id'));
CREATE INDEX idx_doc_members ON document USING GIN((document->'members'));
CREATE INDEX idx_doc_subjects ON document USING GIN((document->'subjects'));
CREATE INDEX idx_doc_resources ON document USING GIN((document->'resources'));
CREATE INDEX idx_doc_actions ON document USING GIN((document->'actions'));
```

**Comment by aeneasr** [comment]
Thank you for your work on this! As explained in the other issue https://github.com/ory/keto/issues/187#issuecomment-614827225 we haven't been able yet to move forward with the project. I think filtering is something very basic and should be supported, we need however a consistent strategy on how that querying works. Because that's not the case (it's also not the case for other projects like Hydra!) I feel uncomfortable with merging changes like this, because we most likely will have to remove them once we find a consistent solution.

Our current thinking goes towards an additional GraphQL API that makes querying easier and consistent. Plain REST is just not good at doing that.

Regarding performance, I completely agree. As pointed out in the other issue this is a big problem right now and needs to be addressed on an architectural level by removing OPA.

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
