### ISSUE TITLE
illegal base64 data at input byte 80

### ISSUE THREAD

**Issue by andyyumiao** [ory/keto#232]
I got the issue when run this command: ./keto serve --config /Users/yumiao3/workspace/github/keto/config.yaml

Unable to load HTTP TLS certificate(s): unable to base64 decode the TLS certificate: illegal base64 data at input byte 80

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.
