### ISSUE TITLE
roles without members does not shown in roles list

### ISSUE THREAD

**Issue by alex-vento** [ory/keto#27]
Hello! In our case we have some roles without members and its does not shown in roles list, but if request an empty role detail page by its id, all works fine

**Comment by sadysnaat** [comment]
I think this is because keto selects roles from keto_role_member table, and not from  keto_role table

https://github.com/ory/keto/blob/48dd9f1ffbeaa99ac8dc27085c5a50f9244bf9c3/role/manager_sql.go#L63-L70

https://github.com/ory/keto/blob/48dd9f1ffbeaa99ac8dc27085c5a50f9244bf9c3/role/manager_sql.go#L185-L191

**Comment by arekkas** [comment]
Yeah, seems like a bug! Thanks for reporting and investigating!
