### ISSUE TITLE
Define naming conventions for objects, relations, namespaces

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#288]
**Is your feature request related to a problem? Please describe.**

Extract these with citations from the paper and document them - both in tests as well as documentation and examples.

**Comment by zepatrik** [comment]
The grammar of the language defined in the paper:

> ```
> <tuple> ::= <object>#<relation>@<user>
> <object> ::= <namespace>:<object_id>
> <user> ::= <user_id> | <userset>
> <userset> ::= <object>#<relation>
> ```

I decided to use `subject` instead of `user` because it is more descriptive IMO. Especially when you consider that a userset can also have the `...` relation which means any relation and basically allows the subject to be an object. See Table 1, last example:

> Example Tuple in Text Notation | Semantics
> --- | ---
> ... | ...
> `doc:readme#parent@folder:A#...` | doc:readme is in folder:A
>
> Table 1: Example relation tuples. “#...” represents a relation that does not affect the semantics of the tuple.

Vote :+1: for `subject`, :-1: for `user`

**Comment by robinbraemer** [comment]
Good, this would effectively mean, or if not considered yet please do so, that we entirely discard the word "user" from our dictionary to consistently knock out any confusion, right?

So that we have:
```
<tuple> ::= <object>#<relation>@<subject>
<object> ::= <namespace>:<object_id>
<subject> ::= <subject_id> | <subjectset>
<subjectset> ::= <object>#<relation>
```
If so, we can finally refactor `UserID` and `UserSet` to `SubjectID` and `SubjectSet` in the current code.

**Comment by robinbraemer** [comment]
# New name of "Zookie" used in the Keto project

As per discussion from:
- https://github.com/ory/keto/issues/311#issuecomment-728162933 ...

We (@zepatrik https://github.com/ory/keto/issues/311#issuecomment-728842524, @tacurran https://github.com/ory/keto/issues/311#issuecomment-727615735, and @robinbraemer ) want to give the "Zookie" from the Zanzibar paper a **new** and more **descriptive** name being very self explanatory as it will be used in our docs es well.

> A Zookie is an opaque consistency **token** to each **snapshot** content version of a relation tuple.

These are the current options to vote for (react to vote):
- 👍 Snaptoken (@robinbraemer)
- 😄 Kookie (@robinbraemer) 
- 🎉 Ketokie (@robinbraemer)
- 🚀 Yotta (@tacurran)
- 👀 Zoery (@tacurran)
- ❤️ Manna (@tacurran)

You can also suggest even better names.

**Comment by robinbraemer** [comment]
As per https://github.com/ory/keto/pull/324#issuecomment-730416135 the RelationTuple's Object will be flattened out and the fields moved one layer up.
- The `object_id` string field will be renamed to `object` string field.
- The namespace relationship will now concentrate on RelationTuples instead of Objects.
