### ISSUE TITLE
Design decisions, Clarifications and Proposals

### ISSUE THREAD

**Issue by robinbraemer** [ory/keto#307]
# Abstract

This document contains proposals, design as well as implementation decisions
and will be extended and rewritten in the cycle of development of Keto's underlying
ACL system.

> This document's authors:
> - [robinbraemer](https://github.com/robinbraemer)

Curated list of projects with similar goals:
 - https://github.com/robinbraemer/zenia

# Design decisions	

The ACL system in Keto is based off of the Google Zanzibar
[paper](https://research.google/pubs/pub48190/).

## Clarification of "subject" vs. "user"

> TL;DR
> - Use "User", which is more concrete
> - Do not mislead that UserID and UserSet are a Subject as these are very different
>contexts with different complexities.
> - Rename the Subject interface **and** make it **very internal**
>  - or remove the interface entirely

Right now the code uses the terms "Subject" to interface/abstract a
"UserID" vs a "UserSet". This adds a named third layer on top.

Adding and using such an interface with its name on top may
considerably cause confusion to developers using our package
and result in external or in-tree code comments that refer to
a Subject, but actually mean a UserSet or UserID, or refer to multiple
Subjects, but actually mean a UserSet array/slice
`[]UserSet`, but not a `[]Subject` or vice-versa.

This may hinder the overall design and goal to stay simple and consistent,
e.g. wouldn't a set of subjects not be called a SubjectSet?
Nevertheless, the Subject interface is an abstraction of a concrete user,
the "UserID" vs a set of users that are not even user IDs,
but a "UserSet" in its own is an Object+Relation that expands to more tuples
that are pointers to either an exact UserID or expand to more tuples.

While each one of the types contain "User" in the name,
they should be looked at from a different perspective and be considered
a completely different concept also with a different complexity when
implemented in the system.

One could argue that the term "user" (as in the Zanzibar paper for ACL space)
is shorter as a word, as well as more concrete in what it is and does:
"A user `uses` the object/resource to do something on/with it."
You see there is a more clear separation of the actual "User" and an object,
where a	"Subject" can also mean an object.

## Don't make "things" dependent on the project name

Something I often see is code that has or produces **fixed** digital objects,
such as database tables, that include the project's name.

There are many reasons why this should not be done on most cases
and there are many examples where this is not done where one concrete
example would be the Google Kubernetes API where
there is a [`ClusterManager`](https://github.com/googleapis/googleapis/blob/b1e1e0b13b580d8fb7a641978198fc8de7228b2f/google/container/v1/cluster_service.proto#L35),
not a `KubernetesManager`.

Yes it highly depends on in which context the "thing" is,
but there are other reasons. Developers want to make sure they
use the shortest and abstracted but meaningful term for their "thing"
while staying flexible enough and don't make their "thing"
dependent on the project name in case it changes.

Projects get forked, renamed and code gets re-used in other projects.
Try not to include your project's name in our "thing"'s name!

**Keto:**
- replace "keto_" table prefix in ["keto_%s_relation_tuples"](https://github.com/ory/keto/blob/3251ca3c2f5056bcda22b9785324e319d54a68ac/persistence/sql/namespace.go#L26)
  with preferably "relation_tuple_%s" or less preferably "%s_relation_tuple"

## Database

- Table names in singular
  - [Here is why!](https://stackoverflow.com/a/5841297/10937429)
  - [Tables vs RESTful resources](https://softwareengineering.stackexchange.com/questions/290646/why-does-convention-say-db-table-names-should-be-singular-but-restful-resources#:~:text=It's%20a%20pretty%20established%20convention,resource%20names%20should%20be%20plural.)

## Storing a UserID and a UserSet in the data store

Currently, the user (yet subject) in the relation tuple table
gets stored under a single column and either contains the
concrete user id or the `<object>#<relation>` UserSet that points
to inherit other users or UserSet tuples.
This column is included in the primary key.

I propose to add four additional columns to the table that will
allow for efficient querying/filtering by UserSet's relation, object & namespace
as well as improve the efficiency for future analytics jobs for analyzing
trees relationships between tuples.

New table schema:
```sql
CREATE TABLE relation_tuple_%namespace%
(
    shard_id    VARCHAR(64),
    object_id   VARCHAR(64),
    relation    VARCHAR(64),
    "user"      VARCHAR(128),
    commit_time TIMESTAMP,
    
    user_id                  VARCHAR(64),
    userset_object_namespace VARCHAR(64),
    userset_object_id        VARCHAR(64),
    userset_relation         VARCHAR(64),

    PRIMARY KEY (shard_id, object_id, relation, "user", commit_time)
);
```
- `user` can be `object_id#relation` or `user_id`
  - this column will still be used in ACL checks
- Note: The columns in the second block are optional,
  in which the `user_id` column is only ever set when relating to an exact user.
  For a UserSet tuple the `user_id` column **must** be null and the `userset_...` columns must be set.

This provides aforementioned benefits since this data now is
hold by the database in efficient binary encodings.
It will also allow us to support more fine-grained filter parameters to the ACL API.

## Prepared statements

- try to use prepared statements where possible
	- otherwise, parse unpredictable statements using a template engine
	  to efficiently generate the SQL queries
	- https://github.com/valyala/fasttemplate

**Comment by aeneasr** [comment]
Nice, I will give this a thorough read tomorrow!

**Comment by robinbraemer** [comment]
This is also more or less a draft of such paper and has just some points.
I expect that implementation details will get added in details by others and me as we develop Keto's ACL system.

**Comment by robinbraemer** [comment]
@everyone
Please put ideas, suggestions and/or improvements directly related to my RFC right here in this issue.
Otherwise, please see the already existing issues in the [Next Gen project board](https://github.com/ory/keto/projects/1) and do open new issues where it makes sense per the different topics my RFC hits.

For other engagements, please see [this discussion](https://ory-community.slack.com/archives/C012RBZFMDG/p1605014595048500) on Ory's Slack!

**Comment by aeneasr** [comment]
> User vs Subject

A user typically refers to a human while an ACL system can also interact with e.g. Service Accounts. Common terms are "subject", "user", "principal", or "identity".

In ORY Hydra we have "subjects" (because that is how OIDC defines it), in ORY Kratos we have "identities" and in ORY Oathkeeper we have also "subjects". I think it would make sense to stay consistent here, while on the other side it would make sense to follow the paper as close as possible, given that the authors probably had these discussions as well.

> Database tables

We're actually not consistent here, ORY Kratos doesn't prefix its tables while ORY Hydra does. The problem with non-prefixed tables is that you can collide with tables from other systems - even the DBAL itself (e.g. information_schema) which is why it is usually very common to prefix them. It also allows running multiple systems in the same table space which is what some people might want (e.g. to keep cost down).

> Singular table names

This again is not consistent in our ecosystem. ORY Hydra uses singular table names while ORY Kratos doesn't. Reason being that it is common practice for gobuffalo/pop to use plural, while I also agree that singular is a bit more convenient I have no strong opinions here.

> Storing a UserID and a UserSet in the data store

I generally agree with this. One issue I see however is that we change the format based on one variable (`user_id`) and validating this across a large database might be very costly. Plus, we get potentially very sparse userset columns as many of them will be NULL.

We could also create a secondary table which holds this "meta" information.

**Comment by robinbraemer** [comment]
Thank you for the feedback and information about the routes other ORY projects chose!

Let's put it all together in #288 and clarify our decisions, that we can fix the implementation and later write ORY user documentation around it. :D @aeneasr @zepatrik

**Comment by tacurran** [comment]
> Singular table names
I suggest that we adhere to the conventions used in SQL, based on (https://en.wikipedia.org/wiki/Relational_algebra) and for singular table and view names. We should also make this a consistent and standard convention across the Ory ecosystem. At present there is https://github.com/ory/keto/issues/288 that should perhaps be mirrored or moved here https://github.com/ory/meta to apply to other Ory projects. Besides singular names, Ory projects use Camel case conventions across the board.
Regarding the REST conventions, here we are dealing with conceptual mapping of entities. Resources are not tables (Cartesian products), and REST conventions use URIs (aka IDs) and URN based on hypertext conventions than on relational algebra. For instance api.../users is a collection of user, and api.../users/{id} is one user. Often this gets confusing for example api.../persons is a collection of person, and api.../persons/{id} is one person. We avoid using people because "persons" sounds like a collection of "person" and is less confusing than "people". We thought about some URN conventions in the past, but without any real effort to think through what that would mean for a larger network and namespace.  For instance urn:oryid:foo-foo-foo-foo-foo

> Don't make "things" dependent on the project name
"Something I often see is code that has or produces fixed digital objects, such as database tables, that include the project's name."  I agree. This is a special case for Hungarian Notation that is no longer used. This convention has to do with the project structure in Ory, and been useful so far. We would benefit from a directory table in /ory/meta to simplify the code for contributors.

**Comment by aeneasr** [comment]
> I see this point. Now the question is, do we support Keto users to clash all tables into one database / (postgres schema)?
I would be against it, since it's an anti pattern and against the microservices design.

The constraint is an artificial one, and prefixing project names actually does prevent name collisions. Real world applications unfortunately mean that people deploy things in the same table space sometimes and while it might not be "best practice" when it comes to separation of concerns, it's the reality many developers face in companies and real world applications. Unfortunately (thankfully?), not everyone operates on Google scale with hundreds of ops teams where spinning up a db instance or a schema is sort of a no-brainer, or some don't even have any microservices and don't want to change their operations stack.

The purpose of the Ory stack is to support both of these environments, especially if the decisions to be made are aesthetic/artistic. We would obviously not use JavaEE, but prefixing tables with the project name is a tradeoff we can do, which makes people's lives so much easier.

**Comment by robinbraemer** [comment]
Has been worked through
