### ISSUE TITLE
Add common helpers to gRPC client package

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#554]
**Is your feature request related to a problem? Please describe.**

Because of the sometimes quite nested structure of messages, there are some pieces of code I keep copying, e.g.

```go
func InsertRelationTuples(rts []*acl.RelationTuples) []*acl.RelationTupleDelta {
	deltas := make([]*acl.RelationTupleDelta, len(rts))
	for i := range rts {
		deltas[i] = &acl.RelationTupleDelta{
			Action:        acl.RelationTupleDelta_INSERT,
			RelationTuple: rts[i],
		}
	}
	return deltas
}
```

**Describe the solution you'd like**

It would be nice to have them added to the generated `acl` package as helpers.

**Describe alternatives you've considered**

A separate helper package outside of `internal` that only depends on `acl`.

**Additional context**

Is there any downside of adding such helpers to the generated `acl` package @robinbraemer ?

**Comment by robinbraemer** [comment]
Mixing generated code files and written helpers may lead to someone accidentally deleting the helper files when deleting the dir to regenerate the proto (e.g. a proto message was removed and must now be deleted manually from the gen package), however, it might be just okay, and since helpers would be easier to find from the same package+version we have to maintain fewer packages at the end.

I don't think there is a problem with it. :+1:  Of course, the same helpers would be required in every version package (`acl/v1alpha1`) to use its versioned struct types respectively.

**Comment by zepatrik** [comment]
Thanks, that makes sense. I also like the idea of having the helpers tied to the version, as that is required anyways. Checking that they will not be deleted should be possible to do during PR reviews, so I don't think it will be an issue.
