### ISSUE TITLE
namespace validate not working for keto.yml

### ISSUE THREAD

**Issue by arigon** [ory/keto#586]
**Describe the bug**

using `keto namespace validate` only works for isolated namespace files and not for the keto.yml

**Expected behavior**

The validator should recognize only the _namespaces_ property of the keto.yml and validate it.

**Additional context**

```
The configuration contains values or keys which are invalid:
(root)
^-- additionalProperties "version", "dsn", "serve", "profiling", "log", "namespaces" not allowed
```

**Comment by cramja** [comment]
Hi, I've been reading the keto codebase, and I'm curious try this as a first contribution (learning Go in order to read this project)

Intro aside, curious about the expected behavior here. We could detect if a given file is a config file based on the presence of a key called `namespaces` and then parse out the namespaces from there. My guess is that most users will only have a single config file so the command should work like

```
./keto validate config.yaml

OR

./keto validate ns1.yaml ns2.yaml

BUT NOT

./keto validate ns1.yaml config.yaml

AND NOT

./keto validate config.yaml config2.yaml
```

What do you think?

Here's a [hacky branch](https://github.com/cramja/keto/commit/ec2738d93b4ad0a05bc27d9753d9ffe45abaef1a) I used to see how quick it was getting started on this project.

**Comment by zepatrik** [comment]
Awesome, your interpretation looks right. Either, the file is going to be a namespace config file or a root config file containing a pointer to the namespace config file(s) (or the namespace config itself). Duck typing as you proposed seems good :+1: 
Looking forward for your PR :wink:

**Comment by cramja** [comment]
I updated the working branch this morning with code that handles for a config file containing a list of namespace definitions (as opposed to a websocket URL). I will look into adding the websocket validation once I get some more time.

Curious what's the more popular way to configure keto?

**Comment by zepatrik** [comment]
> Curious what's the more popular way to configure keto?

Good question, for me inline because it is less steps. But that is only because the namespace config currently is very limited. With #466 and stuff it will become pretty long at some point.
