### ISSUE TITLE
Ensure namespace manager reload context is not leaked

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#642]
**Is your feature request related to a problem? Please describe.**

The config provider creates a new context and cancel func for the namespace manager. We don't have a test that ensures this context is not leaked.

**Describe the solution you'd like**

Add a test to ensure no context leak happens.

**Describe alternatives you've considered**

Rewrite code to not create a new context.

**Comment by aeneasr** [comment]
There are several related things:

- [ ] If the context is canceled, is everything cleaned up properly or do we keep things around which we forgot (memory leak)?
- [ ] When we initiate a new manager, is the CPU spiking because it has lots to do?
- [ ] If we are watching the FS, are we freeing up the inodes and watchers and closing the files?
