### ISSUE TITLE
Graph database (Dgraph, Neo4j) support

### ISSUE THREAD

**Issue by alifpay** [ory/keto#660]
**Is your feature request related to a problem? Please describe.**

I think, graph database fits for access management. Dgraph, Neo4j

https://gist.github.com/achmadns/40fe5073cadd2f6dd797f67872d93420

**Comment by zepatrik** [comment]
Thanks for that link :+1: 
I assume this is similar to what @christian-roggia was talking about?

The basic idea of zanzibar/Keto is exactly that, modeling ACL as a graph of permissions. We should definitely evaluate using a graph database further, but from a quick research there is none really capable of the globally distributed operation we have at CRDB, Yugabyte or Spanner. Effectively we are doing graph queries over typical SQL databases with all of their features.
Also I don't see how one could implement something as subject set rewrites #263 because the graph database can only work with data it already has right?

CC @jon-whit @aeneasr maybe interesting read for you as well

**Comment by aeneasr** [comment]
Probably a better fit would be https://github.com/cayleygraph/cayley as - iirc - allows different storage backends and just abstracts the querying. Was originally in the gGH google org. Website is currently down though :/

**Comment by christian-roggia** [comment]
I would like to suggest [dgraph](https://dgraph.io/) as a native graph database for experimentations as it can scale horizontally (and I believe it has multi-region support) and is ready for production. Additionally, this database was originally developed internally at Google (same as cayley) and received a multi-million round of investment to continue with their development. A downside of dgraph is that it doesn't support SQL as it is a native graph database with no underlying RDBMS (it uses a key-value known as BadgerDB instead, also developed by the dgraph team) but uses instead DQL and GraphQL as query languages.

You can find our experimental RBAC implementation with dgraph here if you are interested to learn more about it and play around: https://github.com/grbac/grbac the way we solve authorization query checks is through  the [Dijkstra's algorithm
](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) to find the shortest path in a graph from a resource (object) to a principal (subject) given a permission (relation).

**Comment by raymondbernard** [comment]
Just my two cents, I have worked with both and really like https://entgo.io/  .  It's a orm for graphs supported by  Facebook.  100 percent open source.  Makes Simple API for modeling any database schema as Go objects
Easily Traverse Any Graph →
Run queries, aggregations and traverse any graph structure easily
Statically Typed And Explicit API →
100% statically typed and explicit API using code generation

**Comment by christian-roggia** [comment]
We experimented with entgo half a year ago and migrated all our ORMs to that framework. My only regret was not discovering it earlier.
