### ISSUE TITLE
Module found (v0.5.2), but does not contain package

### ISSUE THREAD

**Issue by chinhnguyentrung** [ory/keto#693]
**Describe the bug**
github.com/ory/keto/internal/expand: module github.com/ory/keto@latest found (v0.5.2), but does not contain package github.com/ory/keto/internal/expand

**Reproducing the bug**

I'm having a problem with the Extension API.  When I'm trying to run the following code:
```go
package main

import (
	"context"
	"encoding/json"
	"os"

	"github.com/ory/keto/internal/expand"

	"google.golang.org/grpc"

	acl "github.com/ory/keto/proto/ory/keto/acl/v1alpha1"
)

func main() {
	conn, err := grpc.Dial("127.0.0.1:4466", grpc.WithInsecure())
	if err != nil {
		panic(err)
	}

	client := acl.NewExpandServiceClient(conn)

	res, err := client.Expand(context.Background(), &acl.ExpandRequest{
		Subject: &acl.Subject{
			Ref: &acl.Subject_Set{Set: &acl.SubjectSet{
				Namespace: "files",
				Object:    "/photos/beach.jpg",
				Relation:  "access",
			}},
		},
		MaxDepth: 3,
	})
	if err != nil {
		panic(err)
	}

	tree, err := expand.TreeFromProto(res.Tree)
	if err != nil {
		panic(err)
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(tree); err != nil {
		panic(err.Error())
	}
}
```

**Comment by zepatrik** [comment]
This is form one of the code samples right? The right Keto version would be https://github.com/ory/keto/tree/v0.6.0-alpha.3, so I assume you have the wrong version in your `go.mod`.
Anyway, the internal API is not meant to be imported outside of Keto. I know that this is the fault of the code sample, so this issue is more about changing those to not use internal packages.
