### ISSUE TITLE
Doc and implement do not match for delete tuple REST API.

### ISSUE THREAD

**Issue by counter2015** [ory/keto#695]
**Describe the bug**

In [RESTAPI doc](https://www.ory.sh/keto/docs/reference/rest-api#delete-a-relation-tuple)

It says parameter `subject` is not required.

But in code here

https://github.com/ory/keto/blob/2e93d996576842707f7c65dd7b5d7bd0c917331b/internal/persistence/sql/relationtuples.go#L178-L192

`whereSubject`  verify `subject` 

https://github.com/ory/keto/blob/2e93d996576842707f7c65dd7b5d7bd0c917331b/internal/persistence/sql/relationtuples.go#L172-L173

**Reproducing the bug**
![image](https://user-images.githubusercontent.com/13608862/132491426-44fc218f-f738-4ef6-a047-43a6944fb1a7.png)

**Expected behavior**

It should work well

**Environment**

- Version: 0.6.0-alpha.3

**Comment by zepatrik** [comment]
With #729 the subject is now either `subject_id` or (`subject_set_namespace` and `subject_set_object` and `subject_set_relation`). This can however not be properly modeled by swagger 2, so we have to push this back until we migrate to swagger 3 (OpenAPI). However, #718 already fixed the error code, so in that case we return `403` instead of `500`.

**Comment by kmherrmann** [comment]
Closed due to inactivity.

**Comment by kmherrmann** [comment]
@zepatrik is this still current?

**Comment by zepatrik** [comment]
I think we can close this.
